title: Sherpa Documentation
description: Documentation site for Sherpa from Escape Technology.
url: "" # Update this with your GitHub Pages URL (e.g., https://username.github.io)
baseurl: "" # Update this if your site is in a subdirectory (e.g., /sherpa-docs)

theme: just-the-docs

color_scheme: sherpa

logo: "/assets/images/SherpaBlack.png"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: pretty

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md

